#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#---

for region in $(foamListRegions); do
    [ -d "0/$region" ] && rm -rf "0/$region"
done

runApplication blockMesh
runApplication -s air        surfaceFeatureExtract -dict system/surfaceFeatureExtractDict.air
runApplication -s heatSource surfaceFeatureExtract -dict system/surfaceFeatureExtractDict.heatSource
runApplication -s heatSink   surfaceFeatureExtract -dict system/surfaceFeatureExtractDict.heatSink
runApplication -s basis      surfaceFeatureExtract -dict system/surfaceFeatureExtractDict.basis
runApplication snappyHexMesh -overwrite
runApplication splitMeshRegions -cellZones -overwrite

for region in $(foamListRegions); do
    runApplication -s "$region" changeDictionary -region "$region"
done

runApplication decomposePar -allRegions

runParallel chtMultiRegionFoam
